"""empty message

Revision ID: 343f5cf6cff3
Revises: c9827444c649
Create Date: 2025-03-11 00:53:20.722542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343f5cf6cff3'
down_revision = 'c9827444c649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('housekeeper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('id_branche', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_branche'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('housekeeper')
    op.drop_table('branches')
    # ### end Alembic commands ###
